apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: reddit-kafka
  name: reddit-kafka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reddit-kafka
    spec:
      containers:
      - command:
        - bash
        - -c
        - |
          echo 'api stream start up...'
          ./reddit-kafka my-release-kafka.default.svc.cluster.local:9092
        image: gcr.io/<project-id>/reddit-kafka:latest
        name: reddit-kafka

        resources: {}
      restartPolicy: Always
status: {}
